using System;
using System.Collections.Generic;
using System.Linq;
using System.IO;
using System.Text;

namespace AinDecompiler.Compiler
{
    public enum TokenType
    {
        Identifier,

        If,
        Else,
        While,
        Do,
        For,
        Goto,
        Break,
        Continue,
        Struct,
        Class,
        Public,
        Private,
        Functype,
        Delegate,
        Return,
        Switch,
        Case,
        Default,
        New,
        Jump,
        Jumps,
        Const,
        Assert,

        Void,
        Int,
        Float,
        String,
        Bool,
        Lint,
        IMainSystem,

        Array,
        Ref,

        /*
                This,
                Numof,
                Alloc,
                Realloc,
                Free,
                Copy,
                PushBack,
                PopBack,
                LengthByte,
                Empty,
                Length,
                Find,
                GetPart,
                Insert,
                Fill,
                Sort,
                Reverse,
                Erase,
                ConvertToString,
                ConvertToInt,
        */
        Number,
        StringLiteral,
        CharLiteral,
        Message,

        FileMacro,
        LineMacro,
        FuncMacro,
        DateMacro,
        TimeMacro,

        Complement,
        Not,
        At,
        Pound,
        DollarSign,
        DoubleDollarSign,
        Modulo,
        Xor,
        And,
        Multiply,
        OpenParenthesis,
        ClosedParenthesis,
        Minus,
        Plus,
        Assign,
        OpenBracket,
        CloseBracket,
        Or,
        OpenBrace,
        CloseBrace,
        Colon,
        Semicolon,
        LessThan,
        GreaterThan,
        QuestionMark,
        Comma,
        Dot,
        Divide,
        LeftShift,
        RightShift,
        ScopeResolution,
        EqualTo,
        NotEqualTo,
        GreaterThanOrEqualTo,
        LessThanOrEqualTo,
        ModuloAssign,
        AndAssign,
        MultiplyAssign,
        PlusAssign,
        MinusAssign,
        DivideAssign,
        XorAssign,
        OrAssign,
        LeftShiftAssign,
        RightShiftAssign,
        ReferenceAssign,
        ReferenceEqualTo,
        ReferenceNotEqualTo,
        ReferenceSwap,
        Increment,
        Decrement,
        LogicalAnd,
        LogicalOr,
        AddressOf,

        PreIncrement,
        PostIncrement,
        PreDecrement,
        PostDecrement,
        Negative,
        Positive,
        FunctionCall,
        ArrayIndex,

        ClassDefinition,
        ClassDefinitionEntries,
        ClassDefinitionEntry,
        FunctionDeclaration,
        FunctionParameter,
        FunctionParameterList,
        FunctypeParameterList,
        FunctypeParameterEntry,
        VariableInitialValue,
        VariableDeclaration,
        VariableDeclarationList,
        VariableDeclarationEntry,
        ConstDeclaration,
        FunctypeDeclaration,

        Statement,
        Block,

        First,

        Optional,
        Choice,

        ArrayBoundsDeclaration,

        ArrayType,
        FunctionName,
        SimpleDataType,
        DataType,
        Expression,

        BlockOrSingleStatement,
        ExpressionAndSemicolon,

        Label,

        Eof,

        GlobalGroup,
        GlobalGroupDeclaration,
        Hll,
        HllDeclaration,
    }

    public enum RepeatStyle
    {
        RepeatWithCommaUntilCloseParenthesis,
        RepeatWithCommaUntilSemicolon,
        RepeatUntilEndOfBlock,
    }
}
